apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: backend
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
   name: shipping
   namespace: roboshop
   labels:
     component: shipping
     project: roboshop
     tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: backend
    spec:
      containers:
       - name: shipping
         image: mukhtarsheikh/shipping:v1
         envFrom:
            - configMapRef:
                name: shipping  
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:  
    component: shipping
    project: roboshop
    tier: backend
spec:
  selector:
    component: shipping
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
        

    